#!/bin/bash

PWD=$(cd `dirname "$0"`; pwd)

declare -a SPARK_PARAMS 
spark_param_index=0
if [ "$1" == "--spark" ]; then
	shift 1
	while [[ "$#" -gt 0 ]]; do
		arg="$1"
		shift 1
		if [[ "$arg" == "--" ]]; then
			break
		fi
		SPARK_PARAMS[spark_param_index]="$arg"
		((spark_param_index+=1))
	done
fi

spark-submit --class au.csiro.variantspark.cli.VariantSparkApp \
 --driver-class-path ${PWD}/conf \
 "${SPARK_PARAMS[@]}" \
 ${PWD}/target/variant-spark-0.0.1-SNAPSHOT-all.jar "$@"
