#!/bin/bash

PWD=$(cd `dirname "$0"`; pwd)

RUNNER=spark
declare -a SPARK_PARAMS 
spark_param_index=0
if [[ "$1" == "--spark"  || "$1" == "--local" ]]; then
	if [[ "$1" == "--local" ]]; then
		RUNNER=local
	fi
	shift 1
	while [[ "$#" -gt 0 ]]; do
		arg="$1"
		shift 1
		if [[ "$arg" == "--" ]]; then
			break
		fi
		SPARK_PARAMS[spark_param_index]="$arg"
		((spark_param_index+=1))
	done
fi

if [[ "${RUNNER}" == "spark" ]]; then
	spark-submit --class au.csiro.variantspark.cli.VariantSparkApp \
 	--driver-class-path ${PWD}/conf \
 	"${SPARK_PARAMS[@]}" \
 	${PWD}/target/variant-spark-0.0.1-SNAPSHOT-all.jar "$@"
else
	java -cp "${PWD}/conf:${PWD}/target/variant-spark-0.0.1-SNAPSHOT-all.jar:/opt/spark/1.6.1/lib/spark-assembly-1.6.1-hadoop2.2.0.jar:/usr/lib/hadoop/lib/*:/usr/lib/hadoop/.//*:/usr/lib/hadoop-hdfs/./:/usr/lib/hadoop-hdfs/lib/*:/usr/lib/hadoop-hdfs/.//*:/usr/lib/hadoop-yarn/lib/*:/usr/lib/hadoop-yarn/.//*:/usr/lib/hadoop-mapreduce/lib/*:/usr/lib/hadoop-mapreduce/.//*"  au.csiro.variantspark.cli.VariantSparkApp "$@"
fi
