default:
  region: ap-southeast-2
  instanceType: "m4.large"
  ec2Attributes:
    AdditionalMasterSecurityGroups: ['sg-14ffe073']
    KeyName: "default"
    SubnetId: "subnet-01dea958"
    InstanceProfile: "EMR_EC2_DefaultRole"
    EmrManagedSlaveSecurityGroup: "sg-82ffe0e5"
    EmrManagedMasterSecurityGroup: "sg-aefde2c9"
  worker:
    instanceCount: 2
    bidPrice: 0.07
  conf:
    logBucketBase: "au.csiro.pbdava.test/variant-spark"
profiles:
  m4_16xlarge:
    worker:
      instanceType: "m4.16xlarge"
      bidPrice: 0.55
  r4_16xlarge:
    worker:
      instanceType: "r4.16xlarge"
      bidPrice: 0.6
